server/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='home_page'),
    path('about/', views.about_page, name='about_page'),
    path('schedule/', views.schedule_page, name='schedule_page'),
    path('march-schedule/', views.march_schedule_page, name='march_schedule'),
    path('april-schedule/', views.april_schedule_page, name='april_schedule'),
    path('coming-soon/', views.coming_soon, name='coming_soon'),
    path('coach-bios/', views.coach_bios, name='coach_bios'),
    path('coaches-corner/', views.coaches_corner, name='coaches_corner'),
    path('results/', views.results, name='results'),
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

server/main/models.py
from django.db import models

# Create your models here.

server/main/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'main/home-page.html')

def about_page(request):
    return render (request, 'main/school-about-page.html')

def schedule_page(request):
    return render (request, 'main/school-game-schedule.html')

def march_schedule_page(request):
    return render (request, 'main/march-schedule.html')

def april_schedule_page(request):
    return render (request, 'main/april-schedule.html')

def coming_soon(request):
    return render (request, 'main/coming-soon.html')

def coach_bios(request):
    return render (request, 'main/coach_bios.html')

def coaches_corner(request):
    return render (request, 'main/coaches-corner.html')

def results(request):
    return render (request, 'main/results.html')

server/main/templates/main/april-schedule.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.typekit.net/aad5qid.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anta&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% load static%}
    <link rel="stylesheet" type="text/css" href="{% static "/main/css/schedule-april.css" %}">
    <script src="{% static '/main/js/schedule-april.js' %}"></script>
    <title>Schedule Page | JR Hoya CC</title>
</head>
<body>

    <div class="navbar-layout">
        <nav>
            <a href="#"><img src="../static/main/img/logo.jpg" alt=""></a>
        
            <div class="nav-links" id="navLinks">
                <i class="fa fa-times" onclick="hideMenu()"></i>
                <ul>
                    <li><a href="{% url "main:home_page" %}">Home</a></li>
                    <li><a href="{% url "main:about_page" %}">About</a></li>
                    <li><a href="{% url "main:schedule_page" %}">Schedule</a></li>
                    <li><a href="{% url "main:coach_bios" %}">Coach Bios</a></li>
                    <li><a href="{% url "main:coaches_corner" %}">Coach Corner</a></li>
                    <li><a href="{% url "main:results" %}">Results</a></li>
                </ul>
            </div>
        
            <i class="fa fa-bars" onclick="showMenu()"></i>
        
            <script>
                var navLinks = document.getElementById('navLinks');
                function showMenu() {
                    navLinks.style.display = 'block';
                    navLinks.style.right = '0';
                }
        
                function hideMenu() {
                    navLinks.style.display = 'none';
                    navLinks.style.right = '-200px';
                }
            </script>
        </nav>
    </div>


    <div class="div-01-layout">
        <div class="div-01-body">

            <h1>Schedule</h1>

        </div>
    </div>

    <div class="schedule-layout">
        <div class="schedule-body">

            <div class="schedule-title-div">
                <h1 class="title">2024 Schedule</h1>
            </div>

            <div class="card card-01">
                <div class="event-title"><h1>Event Info</h1></div>
                <div class="event-title"><h1>Location</h1></div>
            </div>

            <div class="card card-02">
                <div class="event-item">
                    <h1>Practice</h1>
                    <p>Monday, April 1st, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-03">
                <div class="event-item">
                    <h1>Practice</h1>
                    <p>Thursday, April 4th, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-04">
                <div class="event-item">
                    <h1>Practice / Hurdles</h1>
                    <p>Sunday, April 7th, 2024 at 4:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Harrison High School</h1>

                    <a href="https://www.google.com/maps?daddr=4500+Due+West+Road,+Kennesaw,+GA+30152&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-05">
                <div class="event-item">
                    <h1>Practice</h1>
                    <p>Monday, April 8th, 2024 at 6:00 am</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-06">
                <div class="event-item">
                    <h1>Cartersville Meet</h1>
                    <p>Thursday, April 11th, 2024 at 4:50 pm</p>
                </div>

                <div class="event-location">
                    <h1>Cartersville High School</h1>
                </div>
            </div>

            <div class="card card-07">
                <div class="event-item">
                    <h1>Practice / Hurdles</h1>
                    <p>Sunday, April 14th, 2024 at 4:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Harrison High School</h1>

                    <a href="https://www.google.com/maps?daddr=4500+Due+West+Road,+Kennesaw,+GA+30152&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-08">
                <div class="event-item">
                    <h1>Practice </h1>
                    <p>Monday, April 15th, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-09">
                <div class="event-item">
                    <h1>Practice</h1>
                    <p>thrursday, April 18th, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-10">
                <div class="event-item">
                    <h1>State Meet</h1>
                    <p>Friday, April 19th, 2024</p>
                </div>

                <div class="event-location">
                    <h1>Lilburn, GA</h1>
                </div>
            </div>

            <div class="card card-11">
                <div class="event-item">
                    <h1>State Meet </h1>
                    <p>Saturday, April 20th, 2024</p>
                </div>

                <div class="event-location">
                    <h1>Lilburn, GA</h1>
                </div>
            </div>
        
        </div>
    </div>

    <div class="prev-next-page">
        <a href="{% url 'main:march_schedule' %}"><button>Prev Month</button></a>
    </div>

</body>
</html>

server/main/templates/main/coming-soon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coming Soon</title>
</head>
<body>

    <div class="div-01-layout">
        <div class="div-01-body">
            <h1>Coming Soon</h1>
            <img src="../static/main/img/coming-soon.png" alt="">
        </div>
    </div>
    
    <style>
        .div-01-layout {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .div-01-body {
            text-align: center;
        }
        .div-01-body img {
            width: 50%;
            max-width: 100px;
        }
    </style>
</body>
</html>

server/main/templates/main/march-schedule.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.typekit.net/aad5qid.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anta&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% load static%}
    <link rel="stylesheet" type="text/css" href="{% static "/main/css/schedule-march.css" %}">
    <script src="{% static '/main/js/schedule-march.js' %}"></script>
    <title>Schedule Page | JR Hoya CC</title>
</head>
<body>

    <div class="navbar-layout">
        <nav>
            <a href="#"><img src="../static/main/img/logo.jpg" alt=""></a>
        
            <div class="nav-links" id="navLinks">
                <i class="fa fa-times" onclick="hideMenu()"></i>
                <ul>
                    <li><a href="{% url "main:home_page" %}">Home</a></li>
                    <li><a href="{% url "main:about_page" %}">About</a></li>
                    <li><a href="{% url "main:schedule_page" %}">Schedule</a></li>
                    <li><a href="{% url "main:coach_bios" %}">Coach Bios</a></li>
                    <li><a href="{% url "main:coaches_corner" %}">Coach Corner</a></li>
                    <li><a href="{% url "main:results" %}">Results</a></li>
                </ul>
            </div>
        
            <i class="fa fa-bars" onclick="showMenu()"></i>
        
            <script>
                var navLinks = document.getElementById('navLinks');
                function showMenu() {
                    navLinks.style.display = 'block';
                    navLinks.style.right = '0';
                }
        
                function hideMenu() {
                    navLinks.style.display = 'none';
                    navLinks.style.right = '-200px';
                }
            </script>
        </nav>
    </div>


    <div class="div-01-layout">
        <div class="div-01-body">

            <h1>Schedule</h1>

        </div>
    </div>

    <div class="schedule-layout">
        <div class="schedule-body">

            <div class="schedule-title-div">
                <h1 class="title">2024 Schedule</h1>
            </div>

            <div class="card card-01">
                <div class="event-title"><h1>Event Info</h1></div>
                <div class="event-title"><h1>Location</h1></div>
            </div>

            <div class="card card-02">
                <div class="event-item">
                    <h1>Practice / Hurdes</h1>
                    <p>Sunday, March 3rd, 2024 at 4:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-03">
                <div class="event-item">
                    <h1>Practice / Hurdles</h1>
                    <p>Monday, March 4th, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Harrison High School</h1>

                    <a href="https://www.google.com/maps?daddr=4500+Due+West+Road,+Kennesaw,+GA+30152&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-04">
                <div class="event-item">
                    <h1>Practice </h1>
                    <p>Thursday, March 7th, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-05">
                <div class="event-item">
                    <h1>Marietta Middle School Meet</h1>
                    <p>Saturday, March 9th, 2024 at 10:30 am</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-06">
                <div class="event-item">
                    <h1>Practice / Hurdles</h1>
                    <p>Sunday, March 10th, 2024 at 4:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Harrison High School</h1>

                    <a href="https://www.google.com/maps?daddr=4500+Due+West+Road,+Kennesaw,+GA+30152&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-07">
                <div class="event-item">
                    <h1>Practice </h1>
                    <p>Monday, March 11th, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-08">
                <div class="event-item">
                    <h1>Practice </h1>
                    <p>Thursday, March 14th, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-09">
                <div class="event-item">
                    <h1>Shamrock Shuffle</h1>
                    <p>Saturday, March 16th, 2024</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-10">
                <div class="event-item">
                    <h1>Practice / Hurdles </h1>
                    <p>Sunday, March 17th, 2024 at 4:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Harrison High School</h1>

                    <a href="https://www.google.com/maps?daddr=4500+Due+West+Road,+Kennesaw,+GA+30152&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-11">
                <div class="event-item">
                    <h1>Practice </h1>
                    <p>Monday, March 18th, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-12">
                <div class="event-item">
                    <h1>Cartersville Meet</h1>
                    <p>Thursday, March 21st, 2024 at 5:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-13">
                <div class="event-item">
                    <h1>Practice / Hurdles</h1>
                    <p>Sunday, March 24th, 2024 at 4:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Harrison High School</h1>

                    <a href="https://www.google.com/maps?daddr=4500+Due+West+Road,+Kennesaw,+GA+30152&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-14">
                <div class="event-item">
                    <h1>Practice </h1>
                    <p>Monday, March 25th, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-15">
                <div class="event-item">
                    <h1>Practice </h1>
                    <p>Thursday, March 28th, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

        
        </div>
    </div>

    <div class="prev-next-page">
        <a href="{% url 'main:schedule_page' %}"><button>Prev Month</button></a>
        <a href="{% url 'main:april_schedule' %}"><button>Next Month</button></a>
    </div>

</body>
</html>

server/main/templates/main/school-game-schedule.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.typekit.net/aad5qid.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anta&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% load static%}
    <link rel="stylesheet" type="text/css" href="{% static "/main/css/school-game-schedule.css" %}">
    <script src="{% static '/main/js/school-game-schedule.js' %}"></script>
    <title>Schedule Page | JR Hoya CC</title>
</head>
<body>

    <div class="navbar-layout">
        <nav>
            <a href="#"><img src="../static/main/img/logo.jpg" alt=""></a>
        
            <div class="nav-links" id="navLinks">
                <i class="fa fa-times" onclick="hideMenu()"></i>
                <ul>
                    <li><a href="{% url "main:home_page" %}">Home</a></li>
                    <li><a href="{% url "main:about_page" %}">About</a></li>
                    <li><a href="{% url "main:schedule_page" %}">Schedule</a></li>
                    <li><a href="{% url "main:coach_bios" %}">Coach Bios</a></li>
                    <li><a href="{% url "main:coaches_corner" %}">Coach Corner</a></li>
                    <li><a href="{% url "main:results" %}">Results</a></li>
                </ul>
            </div>
        
            <i class="fa fa-bars" onclick="showMenu()"></i>
        
            <script>
                var navLinks = document.getElementById('navLinks');
                function showMenu() {
                    navLinks.style.display = 'block';
                    navLinks.style.right = '0';
                }
        
                function hideMenu() {
                    navLinks.style.display = 'none';
                    navLinks.style.right = '-200px';
                }
            </script>
        </nav>
    </div>


    <div class="div-01-layout">
        <div class="div-01-body">

            <h1>Schedule</h1>

        </div>
    </div>

    <div class="schedule-layout">
        <div class="schedule-body">

            <div class="schedule-title-div">
                <h1 class="title">2024 Schedule</h1>
            </div>

            <div class="card card-01">
                <div class="event-title"><h1>Event Info</h1></div>
                <div class="event-title"><h1>Location</h1></div>
            </div>

            <div class="card card-02">
                <div class="event-item">
                    <h1>Practice</h1>
                    <p>Thursday, February 1st, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-03">
                <div class="event-item">
                    <h1>Practice / Hurdles</h1>
                    <p>Sunday, February 4th, 2024 at 4:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Harrison High School</h1>

                    <a href="https://www.google.com/maps?daddr=4500+Due+West+Road,+Kennesaw,+GA+30152&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-04">
                <div class="event-item">
                    <h1>Practice </h1>
                    <p>Monday, February 5th, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-05">
                <div class="event-item">
                    <h1>Practice </h1>
                    <p>Thursday, February 8th, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-06">
                <div class="event-item">
                    <h1>Practice / Hurdles</h1>
                    <p>Sunday, February 11th, 2024 at 4:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Harrison High School</h1>

                    <a href="https://www.google.com/maps?daddr=4500+Due+West+Road,+Kennesaw,+GA+30152&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-07">
                <div class="event-item">
                    <h1>Practice </h1>
                    <p>Monday, February 12th, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-08">
                <div class="event-item">
                    <h1>Practice </h1>
                    <p>Thursday, February 15th, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-09">
                <div class="event-item">
                    <h1>Marietta Distance Carnival </h1>
                    <p>Saturday, February 17th, 2024</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-10">
                <div class="event-item">
                    <h1>Practice / Hurdles </h1>
                    <p>Sunday, February 18th, 2024 at 4:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Harrison High School</h1>

                    <a href="https://www.google.com/maps?daddr=4500+Due+West+Road,+Kennesaw,+GA+30152&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-11">
                <div class="event-item">
                    <h1>Practice </h1>
                    <p>Monday, February 19th, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-12">
                <div class="event-item">
                    <h1>Practice </h1>
                    <p>Thursday, February 22nd, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-13">
                <div class="event-item">
                    <h1>Practice / Hurdles</h1>
                    <p>Sunday, February 25th, 2024 at 4:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Harrison High School</h1>

                    <a href="https://www.google.com/maps?daddr=4500+Due+West+Road,+Kennesaw,+GA+30152&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-14">
                <div class="event-item">
                    <h1>Practice </h1>
                    <p>Monday, February 26th, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

            <div class="card card-15">
                <div class="event-item">
                    <h1>Practice </h1>
                    <p>Thursday, February 29th, 2024 at 6:00 pm</p>
                </div>

                <div class="event-location">
                    <h1>Lost Mountain Park</h1>

                    <a href="https://www.google.com/maps?daddr=4845+Dallas+Highway,+Powder+Springs,+GA+30127&t=h" blank="true"><button>Get Directions</button></a>
                </div>
            </div>

        
        </div>
    </div>

    <div class="next-page">
        <a href="{% url 'main:march_schedule' %}"><button>Next Month</button></a>
    </div>

</body>
</html>